---
# BASIC SYSTEM CONFIGURATION

### SANITY CHECKS
- name: Check Ansible version (== 2)
  assert:
    that:
      - ansible_version.major == 2


### BASIC
- name: Generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: yes


### REPOSITORIES
- name: Add UbuntuGIS repository
  apt_repository:
    repo: 'ppa:ubuntugis/ubuntugis-unstable'
    state: present
  become: yes

- name: Add QGIS repository signing key
  apt_key:
    url: http://qgis.org/downloads/qgis-2016.gpg.key
    state: present
  become: yes

- name: Add QGIS repository
  apt_repository:
    repo: 'deb http://qgis.org/{{ qgis_repo }} trusty main'
    state: present
  become: yes


### PACKAGES
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  environment: "{{ proxy_env }}"
  become: yes

- name: Upgrade system
  apt:
    upgrade: full
    force: yes
  environment: "{{ proxy_env }}"
  become: yes

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    force: yes
    install_recommends: no
    state: latest
  environment: "{{ proxy_env }}"
  become: yes


### DIRECTORIES
- name: Create shared development directories
  file:
    path: "{{ synced_folder }}/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - dev/cache/tar
    - dev/cache/pip
    - "dev/publish/{{ ansible_user }}"


- name: Clean local deployment directories
  file:
    path: /home/{{ ansible_user }}/{{ item }}
    state: absent
  with_items:
    - deploy

- name: Create local development directories
  file:
    path: /home/{{ ansible_user }}/{{ item }}
    state: directory
    recurse: yes
  with_items:
    - deploy
    - dev/apps
    - dev/node_modules


# vim: set ts=8 sts=2 sw=2 et:
